// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmpjevixzsjmoseixskk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtcGpldml4enNqbW9zZWl4c2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NjIxMzgsImV4cCI6MjA2NzMzODEzOH0.8PwyyJT8vDsV8KlQR2Vn7U_ONieQxyQzrv4jQla4meQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});